// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/notif-middleware/pkg/db/ent/notifuser"
	"github.com/NpoolPlatform/notif-middleware/pkg/db/ent/predicate"
)

// NotifUserDelete is the builder for deleting a NotifUser entity.
type NotifUserDelete struct {
	config
	hooks    []Hook
	mutation *NotifUserMutation
}

// Where appends a list predicates to the NotifUserDelete builder.
func (nud *NotifUserDelete) Where(ps ...predicate.NotifUser) *NotifUserDelete {
	nud.mutation.Where(ps...)
	return nud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nud *NotifUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(nud.hooks) == 0 {
		affected, err = nud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NotifUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nud.mutation = mutation
			affected, err = nud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nud.hooks) - 1; i >= 0; i-- {
			if nud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (nud *NotifUserDelete) ExecX(ctx context.Context) int {
	n, err := nud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nud *NotifUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: notifuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: notifuser.FieldID,
			},
		},
	}
	if ps := nud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, nud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// NotifUserDeleteOne is the builder for deleting a single NotifUser entity.
type NotifUserDeleteOne struct {
	nud *NotifUserDelete
}

// Exec executes the deletion query.
func (nudo *NotifUserDeleteOne) Exec(ctx context.Context) error {
	n, err := nudo.nud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{notifuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nudo *NotifUserDeleteOne) ExecX(ctx context.Context) {
	nudo.nud.ExecX(ctx)
}
