// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/notif-middleware/pkg/db/ent/notifuser"
	"github.com/google/uuid"
)

// NotifUser is the model entity for the NotifUser schema.
type NotifUser struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID uuid.UUID `json:"app_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotifUser) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case notifuser.FieldCreatedAt, notifuser.FieldUpdatedAt, notifuser.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case notifuser.FieldEventType:
			values[i] = new(sql.NullString)
		case notifuser.FieldID, notifuser.FieldAppID, notifuser.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type NotifUser", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotifUser fields.
func (nu *NotifUser) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notifuser.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				nu.ID = *value
			}
		case notifuser.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				nu.CreatedAt = uint32(value.Int64)
			}
		case notifuser.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				nu.UpdatedAt = uint32(value.Int64)
			}
		case notifuser.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				nu.DeletedAt = uint32(value.Int64)
			}
		case notifuser.FieldAppID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value != nil {
				nu.AppID = *value
			}
		case notifuser.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				nu.UserID = *value
			}
		case notifuser.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				nu.EventType = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this NotifUser.
// Note that you need to call NotifUser.Unwrap() before calling this method if this NotifUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (nu *NotifUser) Update() *NotifUserUpdateOne {
	return (&NotifUserClient{config: nu.config}).UpdateOne(nu)
}

// Unwrap unwraps the NotifUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (nu *NotifUser) Unwrap() *NotifUser {
	_tx, ok := nu.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotifUser is not a transactional entity")
	}
	nu.config.driver = _tx.drv
	return nu
}

// String implements the fmt.Stringer.
func (nu *NotifUser) String() string {
	var builder strings.Builder
	builder.WriteString("NotifUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", nu.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", nu.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", nu.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", nu.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(fmt.Sprintf("%v", nu.AppID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", nu.UserID))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(nu.EventType)
	builder.WriteByte(')')
	return builder.String()
}

// NotifUsers is a parsable slice of NotifUser.
type NotifUsers []*NotifUser

func (nu NotifUsers) config(cfg config) {
	for _i := range nu {
		nu[_i].config = cfg
	}
}
