// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/notif-middleware/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/notif-middleware/pkg/db/ent/readannouncement"
)

// ReadAnnouncementDelete is the builder for deleting a ReadAnnouncement entity.
type ReadAnnouncementDelete struct {
	config
	hooks    []Hook
	mutation *ReadAnnouncementMutation
}

// Where appends a list predicates to the ReadAnnouncementDelete builder.
func (rad *ReadAnnouncementDelete) Where(ps ...predicate.ReadAnnouncement) *ReadAnnouncementDelete {
	rad.mutation.Where(ps...)
	return rad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rad *ReadAnnouncementDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rad.hooks) == 0 {
		affected, err = rad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ReadAnnouncementMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rad.mutation = mutation
			affected, err = rad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rad.hooks) - 1; i >= 0; i-- {
			if rad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rad *ReadAnnouncementDelete) ExecX(ctx context.Context) int {
	n, err := rad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rad *ReadAnnouncementDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: readannouncement.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: readannouncement.FieldID,
			},
		},
	}
	if ps := rad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// ReadAnnouncementDeleteOne is the builder for deleting a single ReadAnnouncement entity.
type ReadAnnouncementDeleteOne struct {
	rad *ReadAnnouncementDelete
}

// Exec executes the deletion query.
func (rado *ReadAnnouncementDeleteOne) Exec(ctx context.Context) error {
	n, err := rado.rad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{readannouncement.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rado *ReadAnnouncementDeleteOne) ExecX(ctx context.Context) {
	rado.rad.ExecX(ctx)
}
